

GET https://gz63cch2tg.execute-api.eu-central-1.amazonaws.com/dev/api/token/4%2F0AX4XfWjpDz2YLAAZpgtQPUOzraHCOD5KXvVH1WFsvrxfKsgUq70HMGNjycvlgxCMw9NPWQ
authority: gz63cch2tg.execute-api.eu-central-1.amazonaws.com
accept: */*
accept-language: en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7
cache-control: no-cache
origin: http://192.168.178.77:8080
pragma: no-cache
referer: http://192.168.178.77:8080/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

###

